const allQuestions = {
  general: {
    easy: [
      { question: "What is the capital of France?", options: ["Berlin", "Madrid", "Paris", "Rome"], answer: 2 },
      { question: "How many continents are there?", options: ["5", "6", "7", "8"], answer: 2 },
      { question: "Which is the largest ocean?", options: ["Atlantic", "Indian", "Pacific", "Arctic"], answer: 2 },
      { question: "Which planet is known as the Blue Planet?", options: ["Mars", "Earth", "Neptune", "Jupiter"], answer: 1 },
      { question: "What is H2O commonly known as?", options: ["Salt", "Water", "Oxygen", "Hydrogen"], answer: 1 },
      { question: "How many days in a leap year?", options: ["365", "366", "367", "364"], answer: 1 },
      { question: "Which is the smallest continent?", options: ["Australia", "Europe", "Asia", "Africa"], answer: 0 },
      { question: "Which is the tallest mountain?", options: ["K2", "Everest", "Kilimanjaro", "Makalu"], answer: 1 },
      { question: "How many colors in a rainbow?", options: ["5", "6", "7", "8"], answer: 2 },
      { question: "Which organ pumps blood?", options: ["Lungs", "Liver", "Brain", "Heart"], answer: 3 },
    ],
    medium: [
      { question: "Which country gifted the Statue of Liberty to the USA?", options: ["UK", "Germany", "France", "Italy"], answer: 2 },
      { question: "What does a barometer measure?", options: ["Pressure", "Temperature", "Speed", "Sound"], answer: 0 },
      { question: "Which desert is the largest?", options: ["Sahara", "Gobi", "Arctic", "Antarctica"], answer: 3 },
      { question: "How many players in a baseball team?", options: ["7", "9", "11", "5"], answer: 1 },
      { question: "What is the national bird of India?", options: ["Sparrow", "Peacock", "Eagle", "Parrot"], answer: 1 },
      { question: "What is the square root of 121?", options: ["9", "11", "13", "15"], answer: 1 },
      { question: "Which is a programming language?", options: ["Python", "Anaconda", "Panda", "Cobra"], answer: 0 },
      { question: "Who is the founder of Facebook?", options: ["Elon Musk", "Mark Zuckerberg", "Bill Gates", "Steve Jobs"], answer: 1 },
      { question: "Which is the largest mammal?", options: ["Elephant", "Whale", "Hippo", "Giraffe"], answer: 1 },
      { question: "What is the boiling point of water?", options: ["90°C", "100°C", "120°C", "80°C"], answer: 1 },
    ],
    hard: [
      { question: "What is the chemical symbol for Gold?", options: ["Ag", "Au", "Gd", "Go"], answer: 1 },
      { question: "Who painted the Mona Lisa?", options: ["Van Gogh", "Da Vinci", "Picasso", "Rembrandt"], answer: 1 },
      { question: "What is the capital of Iceland?", options: ["Oslo", "Reykjavik", "Helsinki", "Stockholm"], answer: 1 },
      { question: "What is the speed of light?", options: ["300,000 km/s", "150,000 km/s", "1,000,000 km/s", "500,000 km/s"], answer: 0 },
      { question: "Which country has won the most FIFA World Cups?", options: ["Germany", "Argentina", "Brazil", "France"], answer: 2 },
      { question: "What is the SI unit of force?", options: ["Joule", "Pascal", "Newton", "Watt"], answer: 2 },
      { question: "Who wrote 'The Odyssey'?", options: ["Homer", "Virgil", "Plato", "Aristotle"], answer: 0 },
      { question: "Which metal is liquid at room temperature?", options: ["Iron", "Mercury", "Copper", "Zinc"], answer: 1 },
      { question: "What does DNA stand for?", options: ["Data Network Architecture", "Deoxyribonucleic Acid", "Digital Nerve Array", "None"], answer: 1 },
      { question: "Which gas is most abundant in the Earth's atmosphere?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], answer: 2 },
    ]
  },
  science: {
  easy: [
    { question: "What planet do we live on?", options: ["Mars", "Earth", "Jupiter", "Venus"], answer: 1 },
    { question: "What gas do humans need to breathe?", options: ["Hydrogen", "Oxygen", "Carbon Dioxide", "Nitrogen"], answer: 1 },
    { question: "Which organ pumps blood in the human body?", options: ["Lungs", "Liver", "Brain", "Heart"], answer: 3 },
    { question: "What do bees collect from flowers?", options: ["Water", "Pollen", "Leaves", "Nectar"], answer: 3 },
    { question: "What is H2O commonly known as?", options: ["Salt", "Water", "Oxygen", "Acid"], answer: 1 },
    { question: "Which planet is known as the Red Planet?", options: ["Earth", "Jupiter", "Mars", "Venus"], answer: 2 },
    { question: "Which sense do we use with our ears?", options: ["Touch", "Taste", "Hearing", "Smell"], answer: 2 },
    { question: "What part of the plant conducts photosynthesis?", options: ["Stem", "Roots", "Flowers", "Leaves"], answer: 3 },
    { question: "How many legs does an insect have?", options: ["4", "6", "8", "10"], answer: 1 },
    { question: "Which is the hottest planet in our solar system?", options: ["Venus", "Mercury", "Mars", "Jupiter"], answer: 0 },
  ],
  medium: [
    { question: "What is the main gas found in the air we breathe?", options: ["Oxygen", "Carbon Dioxide", "Hydrogen", "Nitrogen"], answer: 3 },
    { question: "Which part of the cell contains DNA?", options: ["Ribosome", "Nucleus", "Cytoplasm", "Membrane"], answer: 1 },
    { question: "How many bones are there in the adult human body?", options: ["206", "201", "208", "212"], answer: 0 },
    { question: "What is the boiling point of water in Celsius?", options: ["90°C", "95°C", "100°C", "110°C"], answer: 2 },
    { question: "Which organ is responsible for filtering blood?", options: ["Lungs", "Kidneys", "Heart", "Stomach"], answer: 1 },
    { question: "What is the center of an atom called?", options: ["Electron", "Neutron", "Proton", "Nucleus"], answer: 3 },
    { question: "Which vitamin is produced in the skin in sunlight?", options: ["A", "B", "C", "D"], answer: 3 },
    { question: "What gas do plants absorb from the air?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], answer: 1 },
    { question: "Which scientist proposed the laws of motion?", options: ["Einstein", "Newton", "Tesla", "Galileo"], answer: 1 },
    { question: "What is the name of the largest internal organ in the body?", options: ["Heart", "Liver", "Lungs", "Stomach"], answer: 1 },
  ],
  hard: [
    { question: "What is the unit of electrical resistance?", options: ["Volt", "Ohm", "Watt", "Ampere"], answer: 1 },
    { question: "What is the process of cell division in body cells called?", options: ["Meiosis", "Binary fission", "Mitosis", "Fusion"], answer: 2 },
    { question: "What is the powerhouse of the cell?", options: ["Nucleus", "Mitochondria", "Chloroplast", "Golgi body"], answer: 1 },
    { question: "Who developed the theory of relativity?", options: ["Galileo", "Newton", "Einstein", "Bohr"], answer: 2 },
    { question: "Which blood cells help in clotting?", options: ["Red blood cells", "White blood cells", "Platelets", "Plasma"], answer: 2 },
    { question: "What does DNA stand for?", options: ["Deoxyribonucleic Acid", "Dynamic Nerve Array", "Data Network Algorithm", "None of these"], answer: 0 },
    { question: "Which element has the atomic number 1?", options: ["Oxygen", "Helium", "Hydrogen", "Nitrogen"], answer: 2 },
    { question: "Which part of the brain controls balance?", options: ["Cerebrum", "Medulla", "Cerebellum", "Pons"], answer: 2 },
    { question: "What is the chemical formula of table salt?", options: ["NaCl", "HCl", "KCl", "CaCO₃"], answer: 0 },
    { question: "Which planet has the most moons?", options: ["Earth", "Mars", "Jupiter", "Venus"], answer: 2 },
  ]
},
  history: {
  easy: [
    { question: "Who was the first President of the United States?", options: ["Abraham Lincoln", "George Washington", "Thomas Jefferson", "John Adams"], answer: 1 },
    { question: "In which year did World War I begin?", options: ["1914", "1918", "1939", "1945"], answer: 0 },
    { question: "Who discovered America in 1492?", options: ["Vasco da Gama", "Marco Polo", "Christopher Columbus", "Ferdinand Magellan"], answer: 2 },
    { question: "What was the name of the ship that carried the Pilgrims to America in 1620?", options: ["Santa Maria", "Titanic", "Mayflower", "Endeavour"], answer: 2 },
    { question: "Which wall divided East and West Berlin?", options: ["Berlin Wall", "Iron Curtain", "Great Wall", "Wall of China"], answer: 0 },
    { question: "Who was the Indian leader known for non-violent protests?", options: ["Nehru", "Gandhi", "Bose", "Patel"], answer: 1 },
    { question: "Who was the famous queen of ancient Egypt?", options: ["Cleopatra", "Victoria", "Elizabeth", "Anne"], answer: 0 },
    { question: "The Roman Empire was centered in which modern-day country?", options: ["France", "Italy", "Greece", "Turkey"], answer: 1 },
    { question: "What is the name of the era when dinosaurs lived?", options: ["Ice Age", "Renaissance", "Jurassic", "Medieval"], answer: 2 },
    { question: "Which civilization built the pyramids?", options: ["Greek", "Mayan", "Egyptian", "Roman"], answer: 2 },
  ],
  medium: [
    { question: "What triggered World War II?", options: ["Attack on Pearl Harbor", "Treaty of Versailles", "Invasion of Poland", "Russian Revolution"], answer: 2 },
    { question: "The Cold War was primarily between which two nations?", options: ["USA & UK", "USA & USSR", "China & Japan", "France & Germany"], answer: 1 },
    { question: "Where was Napoleon Bonaparte born?", options: ["France", "Italy", "Corsica", "Austria"], answer: 2 },
    { question: "Which Indian empire was ruled by Ashoka?", options: ["Gupta", "Maurya", "Mughal", "Chola"], answer: 1 },
    { question: "What was the capital of the Mughal Empire?", options: ["Delhi", "Lahore", "Agra", "Kolkata"], answer: 2 },
    { question: "Who was the last Viceroy of British India?", options: ["Mountbatten", "Wellesley", "Curzon", "Cornwallis"], answer: 0 },
    { question: "The Renaissance began in which country?", options: ["France", "England", "Italy", "Spain"], answer: 2 },
    { question: "Who was the leader of the Nazi Party?", options: ["Stalin", "Churchill", "Roosevelt", "Hitler"], answer: 3 },
    { question: "Who wrote the Indian Constitution?", options: ["Gandhi", "Ambedkar", "Nehru", "Tagore"], answer: 1 },
    { question: "The Great Fire of London happened in which year?", options: ["1666", "1766", "1866", "1966"], answer: 0 },
  ],
  hard: [
    { question: "Who was the first Emperor of the Roman Empire?", options: ["Julius Caesar", "Nero", "Augustus", "Caligula"], answer: 2 },
    { question: "Which treaty ended World War I?", options: ["Treaty of Versailles", "Treaty of Paris", "Treaty of Ghent", "Treaty of Tordesillas"], answer: 0 },
    { question: "Who led the Salt March in 1930?", options: ["Sardar Patel", "Jawaharlal Nehru", "Gandhiji", "Bhagat Singh"], answer: 2 },
    { question: "Who was known as the Iron Chancellor of Germany?", options: ["Hitler", "Bismarck", "Goebbels", "Kaiser Wilhelm"], answer: 1 },
    { question: "The Battle of Hastings was fought in which year?", options: ["1066", "1166", "1266", "1366"], answer: 0 },
    { question: "Which explorer completed the first circumnavigation of the Earth?", options: ["Magellan", "Columbus", "Cook", "Da Gama"], answer: 0 },
    { question: "Who was the ruler of England during the Spanish Armada?", options: ["Elizabeth I", "Mary I", "Victoria", "Anne"], answer: 0 },
    { question: "Which dynasty built the Great Wall of China?", options: ["Qing", "Ming", "Han", "Qin"], answer: 3 },
    { question: "The Bolshevik Revolution happened in which country?", options: ["France", "China", "Russia", "Germany"], answer: 2 },
    { question: "Who founded the Maurya Empire in India?", options: ["Ashoka", "Bindusara", "Chandragupta", "Harsha"], answer: 2 },
  ]
},
sports: {
  easy: [
    { question: "How many players are there in a football (soccer) team?", options: ["9", "10", "11", "12"], answer: 2 },
    { question: "Which country is famous for the sport sumo wrestling?", options: ["China", "Korea", "Japan", "Thailand"], answer: 2 },
    { question: "What is the national game of India?", options: ["Cricket", "Hockey", "Football", "Kabaddi"], answer: 1 },
    { question: "Which sport uses a bat, ball, and wickets?", options: ["Baseball", "Hockey", "Cricket", "Tennis"], answer: 2 },
    { question: "How many rings are there in the Olympic symbol?", options: ["3", "4", "5", "6"], answer: 2 },
    { question: "Which sport does Lionel Messi play?", options: ["Tennis", "Cricket", "Football", "Basketball"], answer: 2 },
    { question: "Which country hosted the 2020 Summer Olympics?", options: ["China", "Japan", "Brazil", "USA"], answer: 1 },
    { question: "In tennis, what is the term for a score of zero?", options: ["Love", "Nil", "Zero", "Duck"], answer: 0 },
    { question: "Which sport is played at Wimbledon?", options: ["Football", "Tennis", "Golf", "Rugby"], answer: 1 },
    { question: "What color flag is waved to start a race?", options: ["Red", "Yellow", "Green", "Blue"], answer: 2 },
  ],
  medium: [
    { question: "Who has won the most Grand Slam titles in men's tennis?", options: ["Federer", "Nadal", "Djokovic", "Sampras"], answer: 2 },
    { question: "What is the length of a standard marathon?", options: ["26.2 miles", "25 miles", "20 miles", "30 miles"], answer: 0 },
    { question: "Which country won the FIFA World Cup in 2018?", options: ["Germany", "Brazil", "France", "Croatia"], answer: 2 },
    { question: "Who is known as the Flying Sikh of India?", options: ["Dhyan Chand", "Milkha Singh", "Kapil Dev", "Sachin Tendulkar"], answer: 1 },
    { question: "Which sport uses terms like birdie and eagle?", options: ["Cricket", "Golf", "Tennis", "Baseball"], answer: 1 },
    { question: "What is the maximum score in a single throw in darts?", options: ["60", "100", "50", "80"], answer: 0 },
    { question: "In which sport do teams compete for the Stanley Cup?", options: ["Basketball", "Ice Hockey", "Baseball", "Tennis"], answer: 1 },
    { question: "Which athlete is called the fastest man alive?", options: ["Carl Lewis", "Usain Bolt", "Tyson Gay", "Yohan Blake"], answer: 1 },
    { question: "What is the term for 3 goals by one player in a game?", options: ["Hat-trick", "Triple", "Treble", "Combo"], answer: 0 },
    { question: "How many players are there in a basketball team on the court?", options: ["4", "5", "6", "7"], answer: 1 },
  ],
  hard: [
    { question: "Which cricketer is known as the 'Wall'?", options: ["Sachin Tendulkar", "Rahul Dravid", "Virat Kohli", "MS Dhoni"], answer: 1 },
    { question: "Who was the first Indian to win an Olympic gold medal?", options: ["Abhinav Bindra", "Milkha Singh", "PT Usha", "Leander Paes"], answer: 0 },
    { question: "Which country has won the most Olympic medals?", options: ["Russia", "USA", "China", "Germany"], answer: 1 },
    { question: "In which year was the first modern Olympics held?", options: ["1896", "1900", "1912", "1920"], answer: 0 },
    { question: "Which sport is known as the 'king of sports'?", options: ["Basketball", "Football", "Cricket", "Tennis"], answer: 1 },
    { question: "Which chess grandmaster became world champion at age 22?", options: ["Kasparov", "Fischer", "Carlsen", "Karpov"], answer: 0 },
    { question: "In Formula 1, who holds the record for most championships?", options: ["Ayrton Senna", "Lewis Hamilton", "Michael Schumacher", "Sebastian Vettel"], answer: 1 },
    { question: "Which female athlete has the most Grand Slam titles?", options: ["Serena Williams", "Steffi Graf", "Margaret Court", "Martina Navratilova"], answer: 2 },
    { question: "Where were the first Asian Games held?", options: ["Beijing", "Bangkok", "Tokyo", "New Delhi"], answer: 3 },
    { question: "What is the highest break possible in snooker?", options: ["147", "155", "150", "200"], answer: 0 },
  ]
},
technology: {
  easy: [
    { question: "What does 'CPU' stand for?", options: ["Central Process Unit", "Central Processing Unit", "Computer Processing Unit", "Central Processor Utility"], answer: 1 },
    { question: "Which company makes the iPhone?", options: ["Samsung", "Apple", "Nokia", "Sony"], answer: 1 },
    { question: "Which symbol is commonly used for email?", options: ["#", "@", "$", "&"], answer: 1 },
    { question: "What is the full form of Wi-Fi?", options: ["Wireless Fidelity", "Wired Function", "Wide Frequency", "Wireless Finder"], answer: 0 },
    { question: "Which of these is a search engine?", options: ["Chrome", "Google", "Windows", "Facebook"], answer: 1 },
    { question: "Which key is used to delete characters to the left of the cursor?", options: ["Enter", "Shift", "Backspace", "Ctrl"], answer: 2 },
    { question: "What is the name of Facebook’s parent company?", options: ["Alphabet", "Meta", "X Corp", "ByteDance"], answer: 1 },
    { question: "Which device is used to print documents?", options: ["Scanner", "Printer", "Monitor", "Mouse"], answer: 1 },
    { question: "Which company created Windows OS?", options: ["Apple", "Google", "Microsoft", "Intel"], answer: 2 },
    { question: "What is used to browse websites?", options: ["Operating System", "Browser", "Database", "Compiler"], answer: 1 },
  ],
  medium: [
    { question: "What does HTML stand for?", options: ["HyperText Markup Language", "HighText Machine Language", "Hyper Tabular Markup Language", "None"], answer: 0 },
    { question: "Which programming language is used for Android app development?", options: ["Swift", "Java", "Python", "C#"], answer: 1 },
    { question: "What is the brain of the computer?", options: ["RAM", "Monitor", "CPU", "Keyboard"], answer: 2 },
    { question: "Which port is used to connect pendrives?", options: ["HDMI", "Ethernet", "USB", "VGA"], answer: 2 },
    { question: "What is the full form of URL?", options: ["Uniform Resource Locator", "Unified Result Locator", "Universal Resource Line", "Uniform Result Line"], answer: 0 },
    { question: "Which social media platform is known for short video sharing?", options: ["Instagram", "Twitter", "TikTok", "Facebook"], answer: 2 },
    { question: "What is the name of the AI assistant by Amazon?", options: ["Cortana", "Alexa", "Siri", "Google"], answer: 1 },
    { question: "What does PDF stand for?", options: ["Public Document File", "Portable Document Format", "Print Design File", "Page Description File"], answer: 1 },
    { question: "Which coding language is mainly used for websites?", options: ["C", "Java", "HTML", "Python"], answer: 2 },
    { question: "Which tech giant owns YouTube?", options: ["Amazon", "Meta", "Microsoft", "Google"], answer: 3 },
  ],
  hard: [
    { question: "Who is considered the father of computers?", options: ["Alan Turing", "Charles Babbage", "Bill Gates", "Steve Jobs"], answer: 1 },
    { question: "Which was the first programming language?", options: ["Python", "FORTRAN", "C", "Assembly"], answer: 1 },
    { question: "What does 'AI' stand for in technology?", options: ["Auto Information", "Artificial Intelligence", "Advanced Internet", "Automated Input"], answer: 1 },
    { question: "Which protocol is used to transfer web pages?", options: ["HTTP", "FTP", "TCP", "IP"], answer: 0 },
    { question: "What does 'GPU' stand for?", options: ["Graphical Power Unit", "General Processing Unit", "Graphics Processing Unit", "Graphics Performance Utility"], answer: 2 },
    { question: "Which device is used to connect to the internet?", options: ["Monitor", "Router", "Scanner", "Hard Drive"], answer: 1 },
    { question: "Which data structure uses LIFO?", options: ["Queue", "Stack", "Array", "Tree"], answer: 1 },
    { question: "Who co-founded Microsoft with Bill Gates?", options: ["Steve Wozniak", "Larry Page", "Steve Jobs", "Paul Allen"], answer: 3 },
    { question: "Which operating system is based on Linux?", options: ["iOS", "Android", "Windows", "MacOS"], answer: 1 },
    { question: "What is Git primarily used for?", options: ["Hosting websites", "Version control", "Cloud storage", "Gaming"], answer: 1 },
  ]
},
entertainment: {
  easy: [
    { question: "Who is known as the King of Pop?", options: ["Elvis Presley", "Justin Bieber", "Michael Jackson", "Ed Sheeran"], answer: 2 },
    { question: "Which animated movie features a talking snowman named Olaf?", options: ["Frozen", "Tangled", "Moana", "Brave"], answer: 0 },
    { question: "Which superhero can climb walls?", options: ["Batman", "Superman", "Spider-Man", "Iron Man"], answer: 2 },
    { question: "Which movie series has a character named Harry Potter?", options: ["Twilight", "Lord of the Rings", "Harry Potter", "Narnia"], answer: 2 },
    { question: "What is the name of Mickey Mouse's pet dog?", options: ["Goofy", "Pluto", "Donald", "Scooby"], answer: 1 },
    { question: "Which singer released the song 'Shape of You'?", options: ["Ed Sheeran", "Justin Bieber", "Drake", "Ariana Grande"], answer: 0 },
    { question: "Which movie has the quote 'To infinity and beyond'?", options: ["The Incredibles", "Toy Story", "Monsters Inc", "Cars"], answer: 1 },
    { question: "Who is the female lead in 'Titanic'?", options: ["Kate Winslet", "Emma Watson", "Scarlett Johansson", "Natalie Portman"], answer: 0 },
    { question: "Which show features the characters Joey, Ross, and Rachel?", options: ["Friends", "The Office", "Seinfeld", "How I Met Your Mother"], answer: 0 },
    { question: "Which cartoon features a cat chasing a mouse?", options: ["Tom and Jerry", "Looney Tunes", "Popeye", "Scooby-Doo"], answer: 0 },
  ],
  medium: [
    { question: "Which actor played Iron Man in the Marvel movies?", options: ["Chris Evans", "Chris Hemsworth", "Robert Downey Jr.", "Mark Ruffalo"], answer: 2 },
    { question: "Which band sang 'Bohemian Rhapsody'?", options: ["The Beatles", "Queen", "Coldplay", "One Direction"], answer: 1 },
    { question: "In which year did the first Harry Potter movie release?", options: ["1999", "2000", "2001", "2002"], answer: 2 },
    { question: "Who directed the movie 'Avatar'?", options: ["Steven Spielberg", "James Cameron", "Christopher Nolan", "Peter Jackson"], answer: 1 },
    { question: "Which Indian movie won an Oscar for Best Original Song in 2009?", options: ["Lagaan", "Swades", "Slumdog Millionaire", "Rang De Basanti"], answer: 2 },
    { question: "Which singer is also known as 'Queen B'?", options: ["Beyoncé", "Britney Spears", "Lady Gaga", "Shakira"], answer: 0 },
    { question: "Which show features Eleven and the Upside Down?", options: ["The Flash", "Stranger Things", "Dark", "Lost"], answer: 1 },
    { question: "Which Disney movie is based on a Chinese legend?", options: ["Frozen", "Moana", "Mulan", "Tangled"], answer: 2 },
    { question: "What is the real name of rapper Eminem?", options: ["Marshall Bruce Mathers III", "Curtis Jackson", "Kanye West", "Jay-Z"], answer: 0 },
    { question: "Which movie is based on a dream-sharing technology?", options: ["Inception", "Interstellar", "The Matrix", "Tenet"], answer: 0 },
  ],
  hard: [
    { question: "Which 1994 film won the Oscar for Best Picture?", options: ["Pulp Fiction", "The Shawshank Redemption", "Forrest Gump", "Four Weddings and a Funeral"], answer: 2 },
    { question: "Who composed the music for the 'Star Wars' series?", options: ["Hans Zimmer", "James Horner", "John Williams", "Alan Silvestri"], answer: 2 },
    { question: "Which actor has won the most Academy Awards for acting?", options: ["Meryl Streep", "Daniel Day-Lewis", "Katharine Hepburn", "Jack Nicholson"], answer: 2 },
    { question: "What is the name of the fictional continent in Game of Thrones?", options: ["Westeros", "Valyria", "Essos", "Narnia"], answer: 0 },
    { question: "Who played Joker in 'The Dark Knight'?", options: ["Joaquin Phoenix", "Heath Ledger", "Jared Leto", "Christian Bale"], answer: 1 },
    { question: "Which movie features the character 'Tyler Durden'?", options: ["Fight Club", "Se7en", "American Psycho", "The Godfather"], answer: 0 },
    { question: "Which K-pop band is also known as Bangtan Boys?", options: ["EXO", "BTS", "Blackpink", "TWICE"], answer: 1 },
    { question: "Which director is known for the movies 'Interstellar' and 'Inception'?", options: ["James Cameron", "Christopher Nolan", "Steven Spielberg", "Quentin Tarantino"], answer: 1 },
    { question: "What is the highest-grossing movie of all time (as of 2025)?", options: ["Titanic", "Avengers: Endgame", "Avatar", "The Lion King"], answer: 2 },
    { question: "Which Indian actor is also known as the 'Big B'?", options: ["Shah Rukh Khan", "Aamir Khan", "Amitabh Bachchan", "Salman Khan"], answer: 2 },
  ]
},
math: {
  easy: [
    { question: "What is 5 + 3?", options: ["6", "8", "9", "7"], answer: 1 },
    { question: "What is 10 - 4?", options: ["5", "6", "7", "4"], answer: 1 },
    { question: "What is 2 × 6?", options: ["8", "12", "10", "14"], answer: 1 },
    { question: "What is 12 ÷ 4?", options: ["3", "4", "6", "2"], answer: 0 },
    { question: "Which number is even?", options: ["3", "7", "10", "5"], answer: 2 },
    { question: "What comes after 99?", options: ["98", "100", "101", "97"], answer: 1 },
    { question: "What is the value of π (approximately)?", options: ["2.14", "3.14", "4.14", "5.14"], answer: 1 },
    { question: "Which shape has 3 sides?", options: ["Square", "Triangle", "Circle", "Rectangle"], answer: 1 },
    { question: "What is the half of 20?", options: ["5", "8", "10", "15"], answer: 2 },
    { question: "What is 0 multiplied by any number?", options: ["Same number", "0", "1", "Infinite"], answer: 1 },
  ],
  medium: [
    { question: "What is the square root of 144?", options: ["12", "14", "10", "16"], answer: 0 },
    { question: "What is 15% of 200?", options: ["20", "25", "30", "35"], answer: 2 },
    { question: "Solve: 8²", options: ["56", "64", "72", "60"], answer: 1 },
    { question: "What is the perimeter of a square with side 5?", options: ["20", "15", "25", "10"], answer: 0 },
    { question: "Which is a prime number?", options: ["4", "6", "9", "7"], answer: 3 },
    { question: "What is the value of 3x if x = 4?", options: ["7", "10", "12", "15"], answer: 2 },
    { question: "If a triangle has angles 60° and 60°, what is the third angle?", options: ["30°", "60°", "80°", "90°"], answer: 1 },
    { question: "How many degrees in a right angle?", options: ["45°", "60°", "90°", "180°"], answer: 2 },
    { question: "How many faces does a cube have?", options: ["4", "5", "6", "8"], answer: 2 },
    { question: "What is 1000 divided by 10?", options: ["10", "100", "1000", "90"], answer: 1 },
  ],
  hard: [
    { question: "What is the value of 7³?", options: ["343", "3430", "49", "240"], answer: 0 },
    { question: "What is the derivative of x²?", options: ["x", "2x", "x²", "2"], answer: 1 },
    { question: "What is the area of a circle with radius 3? (Use π ≈ 3.14)", options: ["28.26", "18.84", "9.42", "25.13"], answer: 0 },
    { question: "Solve: 3x - 7 = 11", options: ["6", "5", "7", "9"], answer: 0 },
    { question: "What is the factorial of 5?", options: ["120", "60", "100", "20"], answer: 0 },
    { question: "Which number is a perfect cube?", options: ["8", "16", "18", "20"], answer: 0 },
    { question: "What is the next prime after 29?", options: ["30", "31", "33", "35"], answer: 1 },
    { question: "What is the sum of interior angles of a hexagon?", options: ["540°", "720°", "900°", "1080°"], answer: 1 },
    { question: "What is log₁₀(100)?", options: ["1", "2", "10", "0"], answer: 1 },
    { question: "What is the formula for Pythagoras Theorem?", options: ["a² + b² = c²", "a² - b² = c²", "a² + c² = b²", "b² + c² = a²"], answer: 0 },
  ]
},
literature: {
  easy: [
    { question: "Who wrote 'The Cat in the Hat'?", options: ["J.K. Rowling", "Roald Dahl", "Dr. Seuss", "Mark Twain"], answer: 2 },
    { question: "What is the name of Harry Potter's pet owl?", options: ["Errol", "Hedwig", "Crookshanks", "Scabbers"], answer: 1 },
    { question: "Who is the author of 'Charlie and the Chocolate Factory'?", options: ["Roald Dahl", "Lewis Carroll", "E.B. White", "Dr. Seuss"], answer: 0 },
    { question: "Which fairy tale character leaves a glass slipper at the ball?", options: ["Rapunzel", "Belle", "Cinderella", "Snow White"], answer: 2 },
    { question: "Who wrote 'Romeo and Juliet'?", options: ["William Wordsworth", "William Shakespeare", "Robert Frost", "Emily Dickinson"], answer: 1 },
    { question: "Which animal is the main character in 'Charlotte’s Web'?", options: ["Pig", "Mouse", "Dog", "Cat"], answer: 0 },
    { question: "What is the color of the hat in 'The Cat in the Hat'?", options: ["Red and white", "Blue and white", "Red and black", "Black and white"], answer: 0 },
    { question: "In which book is the character Huckleberry Finn found?", options: ["To Kill a Mockingbird", "The Adventures of Huckleberry Finn", "Moby Dick", "Treasure Island"], answer: 1 },
    { question: "Who wrote 'The Jungle Book'?", options: ["Jules Verne", "Rudyard Kipling", "Lewis Carroll", "Jack London"], answer: 1 },
    { question: "What type of story is a fable?", options: ["Scary", "Funny", "True story", "Moral story with animals"], answer: 3 },
  ],
  medium: [
    { question: "Who wrote 'Pride and Prejudice'?", options: ["Emily Brontë", "Jane Austen", "George Eliot", "Charlotte Brontë"], answer: 1 },
    { question: "What is the full name of the author 'J.K. Rowling'?", options: ["Jane Kate Rowling", "Joanne Kathleen Rowling", "Julia Kristen Rowling", "Janet Karen Rowling"], answer: 1 },
    { question: "Who wrote 'Of Mice and Men'?", options: ["John Steinbeck", "Harper Lee", "F. Scott Fitzgerald", "Ernest Hemingway"], answer: 0 },
    { question: "Which novel begins with the line 'Call me Ishmael'?", options: ["Moby Dick", "Great Expectations", "Jane Eyre", "The Old Man and the Sea"], answer: 0 },
    { question: "Who is the author of '1984'?", options: ["Aldous Huxley", "George Orwell", "Ray Bradbury", "Isaac Asimov"], answer: 1 },
    { question: "In which book do we find the character 'Atticus Finch'?", options: ["The Catcher in the Rye", "To Kill a Mockingbird", "Little Women", "Of Mice and Men"], answer: 1 },
    { question: "Who wrote the poem 'The Raven'?", options: ["Robert Frost", "Walt Whitman", "Edgar Allan Poe", "T.S. Eliot"], answer: 2 },
    { question: "Which author created 'Sherlock Holmes'?", options: ["Agatha Christie", "Arthur Conan Doyle", "Dan Brown", "Charles Dickens"], answer: 1 },
    { question: "Which Shakespeare play features a character named 'Macbeth'?", options: ["Othello", "Hamlet", "Macbeth", "The Tempest"], answer: 2 },
    { question: "Which novel is set on a deserted island?", options: ["Lord of the Flies", "The Great Gatsby", "Wuthering Heights", "Dracula"], answer: 0 },
  ],
  hard: [
    { question: "What is the pen name of Mary Ann Evans?", options: ["George Eliot", "Emily Brontë", "Louisa May Alcott", "George Sand"], answer: 0 },
    { question: "In Dante’s Inferno, how many circles of Hell are described?", options: ["7", "8", "9", "10"], answer: 2 },
    { question: "Who wrote 'The Picture of Dorian Gray'?", options: ["Oscar Wilde", "Franz Kafka", "Bram Stoker", "H.G. Wells"], answer: 0 },
    { question: "What is the name of the monster in Mary Shelley's 'Frankenstein'?", options: ["Dracula", "Victor", "Frankenstein's monster", "Behemoth"], answer: 2 },
    { question: "Which Russian author wrote 'Crime and Punishment'?", options: ["Leo Tolstoy", "Fyodor Dostoevsky", "Anton Chekhov", "Vladimir Nabokov"], answer: 1 },
    { question: "In 'The Great Gatsby', what is Gatsby’s first name?", options: ["James", "Jay", "Jack", "George"], answer: 1 },
    { question: "Which poet wrote 'Do Not Go Gentle Into That Good Night'?", options: ["Robert Frost", "T.S. Eliot", "Dylan Thomas", "W.B. Yeats"], answer: 2 },
    { question: "Which author wrote the epic 'The Aeneid'?", options: ["Homer", "Plato", "Virgil", "Sophocles"], answer: 2 },
    { question: "What is the name of the magical land in 'The Chronicles of Narnia'?", options: ["Oz", "Hogwarts", "Narnia", "Middle Earth"], answer: 2 },
    { question: "Which novel features a whale named Moby Dick?", options: ["Treasure Island", "Moby Dick", "The Sea Wolf", "Captain Blood"], answer: 1 },
  ]
},
geography: {
  easy: [
    { question: "Which is the largest continent?", options: ["Africa", "Asia", "Europe", "Australia"], answer: 1 },
    { question: "Which country is known as the Land of the Rising Sun?", options: ["China", "Japan", "Thailand", "India"], answer: 1 },
    { question: "What is the capital of India?", options: ["Mumbai", "Delhi", "Kolkata", "Chennai"], answer: 1 },
    { question: "Which is the longest river in the world?", options: ["Amazon", "Ganges", "Nile", "Yangtze"], answer: 2 },
    { question: "Which is the largest ocean?", options: ["Atlantic", "Indian", "Pacific", "Arctic"], answer: 2 },
    { question: "Which continent is Egypt in?", options: ["Asia", "Africa", "Europe", "Australia"], answer: 1 },
    { question: "Which country has the Great Wall?", options: ["Japan", "Mongolia", "China", "India"], answer: 2 },
    { question: "Where is Mount Everest located?", options: ["Nepal", "India", "China", "Bhutan"], answer: 0 },
    { question: "Which is the smallest continent?", options: ["Europe", "Australia", "Antarctica", "South America"], answer: 1 },
    { question: "What is the capital of France?", options: ["London", "Berlin", "Madrid", "Paris"], answer: 3 },
  ],
  medium: [
    { question: "Which line divides the Earth into Northern and Southern Hemispheres?", options: ["Prime Meridian", "Tropic of Cancer", "Equator", "International Date Line"], answer: 2 },
    { question: "What is the capital of Canada?", options: ["Toronto", "Vancouver", "Ottawa", "Montreal"], answer: 2 },
    { question: "Which desert is the largest in the world?", options: ["Sahara", "Arctic", "Gobi", "Antarctica"], answer: 3 },
    { question: "Which country has the most number of islands?", options: ["Philippines", "Norway", "Sweden", "Indonesia"], answer: 2 },
    { question: "Which continent is the Sahara Desert located in?", options: ["Asia", "Africa", "Australia", "Europe"], answer: 1 },
    { question: "Which river flows through London?", options: ["Seine", "Danube", "Thames", "Rhine"], answer: 2 },
    { question: "Which U.S. state is the Grand Canyon in?", options: ["Nevada", "Arizona", "Utah", "California"], answer: 1 },
    { question: "What is the capital of Brazil?", options: ["São Paulo", "Brasília", "Rio de Janeiro", "Salvador"], answer: 1 },
    { question: "What ocean is on the east coast of the United States?", options: ["Indian", "Atlantic", "Pacific", "Arctic"], answer: 1 },
    { question: "Which mountain range is the longest in the world?", options: ["Andes", "Rockies", "Himalayas", "Alps"], answer: 0 },
  ],
  hard: [
    { question: "Which country has the most volcanoes?", options: ["Japan", "USA", "Indonesia", "Russia"], answer: 2 },
    { question: "What is the capital of Kazakhstan?", options: ["Almaty", "Astana (Nur-Sultan)", "Tashkent", "Bishkek"], answer: 1 },
    { question: "Which river is known as the Yellow River?", options: ["Yangtze", "Huang He", "Mekong", "Amur"], answer: 1 },
    { question: "What is the name of the strait that separates Asia and North America?", options: ["Bosporus", "Bering Strait", "Magellan", "Gibraltar"], answer: 1 },
    { question: "Which African lake is the world's second largest freshwater lake by surface area?", options: ["Lake Victoria", "Lake Tanganyika", "Lake Malawi", "Lake Chad"], answer: 0 },
    { question: "Which capital city is the highest above sea level?", options: ["La Paz", "Quito", "Kathmandu", "Thimphu"], answer: 0 },
    { question: "Which country is completely landlocked?", options: ["Peru", "Austria", "Pakistan", "Bangladesh"], answer: 1 },
    { question: "What is the smallest country in the world?", options: ["Monaco", "San Marino", "Vatican City", "Liechtenstein"], answer: 2 },
    { question: "What is the deepest ocean trench?", options: ["Tonga Trench", "Kuril-Kamchatka Trench", "Mariana Trench", "Puerto Rico Trench"], answer: 2 },
    { question: "Which European city is split by canals and known as the 'City of Bridges'?", options: ["Venice", "Amsterdam", "Bruges", "Copenhagen"], answer: 0 },
  ]
}

};

